[server]
headless = true
enableCORS = false
port = 8501

[client]
showSidebarNavigation = false
toolbarMode = "viewer"
showErrorDetails = false

[ui]
hideTopBar = true

[browser]
gatherUsageStats = false
